spring:
  datasource:
    url: jdbc:mysql://10.10.10.101:3306/jboot_har?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sisteraram
    password: 12345678
  
  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp" 


mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
  
    
    
logging:
  level:
    org.hibernate: debug
    org.springframework: info
    org.zerock: debug

   
  
    